//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace com.pacyga.enumeration
{
	public class ModeEnum
	{
		public const string PLACE_GAME_OBJECTS = "place_game_objects";
		public const string GAME = "game";
		
		public static readonly List<string> MODES = new List<string>{PLACE_GAME_OBJECTS, GAME};

		public static readonly int MODES_COUNT = MODES.Count;
	}
}

