//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace com.pacyga.enumeration
{
	public class TagsEnum
	{
		public const string PLAYER_GAME_OBJECT = "PlayerGameObject";
		public const string ENEMY = "Enemy";
		public const string BULLET = "Bullet";
	}
}

