//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using com.pacyga.enumeration;

namespace com.pacyga.controller
{
	public class BulletController : MonoBehaviour
	{
		private GameObject _target;

		public float speed = 20f;
		public float attack = 10f;
		public float destroyDelay = 2f;

		void Start()
		{
			Destroy(gameObject, destroyDelay);
		}

		void Update()
		{
			moveToTarget();
		}

		void OnTriggerEnter(Collider other) 
		{
			if (other.gameObject.tag == TagsEnum.ENEMY)
			{
				other.gameObject.GetComponent<TrollController>().health -= attack;
				Destroy(gameObject);
			}
		}

		private void moveToTarget()
		{
			if (_target != null)
			{
				gameObject.transform.position = Vector3.MoveTowards(transform.position, new Vector3(_target.transform.position.x, _target.collider.bounds.size.y, _target.transform.position.z), speed * Time.deltaTime);
			}
		}

		public void setTarget(GameObject  value)
		{
			_target = value;
		}
	}	
}

