//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace com.pacyga.controller
{
	public class LumberyardController : GameObjectController
	{
		private const int GOLD_PRICE = 1500;
		private const int WOOD_PRICE = 0;
		
		protected override void Start()
		{
			base.Start();
			_gameManager.canBuyGameObject = false;
			if (_gameManager.gold >= GOLD_PRICE && _gameManager.wood >= WOOD_PRICE)
			{
				_gameManager.canBuyGameObject = true;
				_gameManager.gameObjectGoldPrice = -GOLD_PRICE;
				_gameManager.gameObjectWoodPrice = -WOOD_PRICE;
			}
		}
		
		override public void onPurchase() 
		{ 
			_gameManager.modifyLumberyards(1);
		}
		
		override public void onDestroy() 
		{ 
			_gameManager.modifyLumberyards(-1);
		}
	}
}

