//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace com.pacyga.controller
{
	public class WallController : GameObjectController
	{
		private const int GOLD_PRICE = 200;
		private const int WOOD_PRICE = 200;

		private const int HEALTH_MULTIPLIER = 10;
		private const int BASE_HEALTH = 100;
		
		protected override void Start()
		{
			base.Start();
			_gameManager.canBuyGameObject = false;
			health = Math.Max(BASE_HEALTH, ((_gameManager.residences * _gameManager.banks * _gameManager.lumberyards) * HEALTH_MULTIPLIER));
			if (_gameManager.gold >= GOLD_PRICE && _gameManager.wood >= WOOD_PRICE)
			{
				_gameManager.canBuyGameObject = true;
				_gameManager.gameObjectGoldPrice = -GOLD_PRICE;
				_gameManager.gameObjectWoodPrice = -WOOD_PRICE;
			}
		}
	}
}

